# Generated by Django 4.1.3 on 2022-11-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default=None, max_length=8, verbose_name='Пол человека'),
        ),
    ]
