# Generated by Django 4.1.3 on 2022-11-13 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_address_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(2022, 11, 14), verbose_name='Дата рождения'),
        ),
    ]
